### ISSUE TITLE
Where is the computation_energy function, I can't find it.

### ISSUE THREAD

**Issue by LuShouPeng** [nizar-masmoudi/decentralized-federated-learning#1]

**Comment by nizar-masmoudi** [comment]
I got rid of the computation energy function because I didn't use it in my project and I didn't want to add confusion. I've added it again.

https://github.com/nizar-masmoudi/decentralized-federated-learning/blob/cf7903b5873df90aead08cc7b6f32b649516303f/client/client.py#L148-L156

**Comment by LuShouPeng** [comment]
> I got rid of the computation energy function because I didn't use it in my project and I didn't want to add confusion. I've added it again.
> 
> https://github.com/nizar-masmoudi/decentralized-federated-learning/blob/cf7903b5873df90aead08cc7b6f32b649516303f/client/client.py#L148-L156


Thank you very much for your prompt reply, your code has given me very great guidance in this direction.
